-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 17:25:33 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `language` (
  `id` CHAR(2) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `synset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `synset` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `original_id` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `positive_score` FLOAT UNSIGNED NOT NULL,
  `negative_score` FLOAT UNSIGNED NOT NULL,
  `gloss` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `language_id` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `original_id_UNIQUE` (`original_id` ASC),
  INDEX `fk_synset_language1_idx` (`language_id` ASC),
  CONSTRAINT `fk_synset_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `language` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `synset_term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `synset_term` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `synset_id` INT(10) UNSIGNED NOT NULL,
  `term` VARCHAR(20) NOT NULL,
  `sense_number` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_synset_term_synset_idx` (`synset_id` ASC),
  CONSTRAINT `fk_synset_term_synset`
    FOREIGN KEY (`synset_id`)
    REFERENCES `synset` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
